apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: btest-alert-2
  namespace: flux-system
spec:
  summary: "Slacktest Helm Notification"
  providerRef: 
    name: slack
  eventSeverity: info
  eventSources:
    - kind: "GitRepository"
      name: "*"
    - kind: "Kustomization"
      name: "*"
      