apiVersion: v1
data:
    address: ENC[AES256_GCM,data:wfk1sBCSGLZ+chYMWGF5S6isC/wnucOZkrSfLtaaNr9b+KlQgV+ZteMFB+YNlhqti1MFgh2Smp9FEeQTMv2f7oF3cFM=,iv:DfLfqJj4nURC2/SKlWOmV0kigKBDDtFuyuH0rDWUZVU=,tag:XQvFi1l5noNITvLOkGhUGQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-url
    namespace: flux-system
# sops:
#     kms: []
#     gcp_kms: []
#     azure_kv: []
#     hc_vault: []
#     lastmodified: '2021-06-04T12:31:53Z'
#     mac: ENC[AES256_GCM,data:Ae6zcEIFXFxnoQhwxX3hRa3LarBiKvSFJuaZiL2ssrDyo7RuovNiLM1Rp5okD2LhB3e+/6rl6GsJojTJwCBuAV+2Aj5L8SUu4pxdanNi8NuL4b3XsBRwRDmhsxwTh2absgyqraGUPH4vkcUGlpLjVoWRQiAURSze+EoRGFdl2Kk=,iv:F21jzuoh9+kRZWOO746IOtKpBBPdYvhWq4SpwdJv17Q=,tag:TMZlxtEdlfnfV5MkaUCnNw==,type:str]
#     pgp:
#     -   created_at: '2021-06-04T12:31:51Z'
#         enc: |
#             -----BEGIN PGP MESSAGE-----

#             hQIMA9aixW2ynRHWAQ/9Goag7Ge/Y17LIFB8JUlyjP9cQOYHEGWrkO5LTAxwaYPN
#             YI0mTkPKxihQB+PYB1lJnjAOLcXSt2dXrb996C5TC/pgiUfe6VFsC1RNYbKRoPBK
#             ci0R6P83CaNAoB3ZMlZ1R7Ga7xEYVeieZFmFXZuFAKHCyhcSSW7oXbpzR1w4A2sz
#             ZddqPSqJZgAP4rw+UQP1Kb4/lcpFUU2b4sPVMoUC1wRHvNLppEHsnncHY8lsKfy3
#             Aax3cEzBNIoiIinMc2ZrQblS1wAqAE+Z/qOEwpxVwN9Oy+Ps6TdfrxsGhZUByqoK
#             m2HjxBVXGYVHnE5s5TG7hnp33rakP5q9TnFPhzHqWO25tLSxlM+kTLKb5ZgGJsW0
#             9+ZrAamA5G28mLg2xmDpTSq0PlC1n3DeRLidpqwSidlRLDkOvcTBAY4nzDSQrnCr
#             sCNC7idfRh0rsN3cEtqTGABi6pEize5LYV7EvEHVGg1+BjYnZyalIxPKyw/R7/Bg
#             /mXZwu7NcGOfmIY+DCoktip16KRBGOPSv+pblQahSe1D9/gRg1w0ewD+EWM1fxRg
#             YabaH+wFEiFAPrnPZRZaWPbkbDLfR13AbC3qOiLXck0Eda8qsztLBMdbcfsMuw3P
#             PhXApicaRB0EybJq4Ktts+y8K37y4y99HukwixOw64FxqMJvWqqp3UZO4IinhtrS
#             XgEeBhdwC2O7Sue/NcbjiBlMFCAP5lykSX4I/vJlXL9SUVOvJywX1ad3o+G8vyt+
#             vNoWbpU2tWq2yShKaM3Itl5KNneczpqh2zYg9ZPQPyOz7do4/WpieerOtmEEmvc=
#             =/xI5
#             -----END PGP MESSAGE-----
#         fp: 22FE5F30631096FFEE7F1E9B40803ABF3FE40332
#     encrypted_regex: ^(data|stringData)$
#     version: 3.6.1
