apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quota.yaml

namespace: integrations
configMapGenerator:
- name: metas
  literals:
  - limits.cpu=16
  - limits.memory=24Gi

replacements:
- source:
    kind: ConfigMap
    name: metas
    fieldPath: data.[limits.memory]
  targets:
  - select:
      name: common
      kind: ResourceQuota
    fieldPaths:
    - spec.hard.[limits.memory]